"""Per-class-day review checklists for the prep packs (PHY 210).

Michael's standing rule (2026-09-07): every PCCI and every in-class
problem must be reviewed BEFORE the class it appears in, and every
homework problem must be reviewed by THE DAY AFTER it is assigned
(assigned = the day the Moodle WHW becomes visible, 10.5 days before it
is due). This script enumerates the PCCI and the WHW tiers per day from
the calendar generator (PCCI, WHWS, the Friday/override due-date rule),
so the lists stay correct when assignments change. In-class problems for
210 are not in the generator (they come from the S26 decks and Berger's
sets, chosen per pack), so each checklist carries a line pointing at the
pack's plan. Rerun after any generator edit:

    python make_review_checklists.py

Writes `01-review-checklist.md` into every existing prep-pack folder and
`REVIEW-SCHEDULE.md` at the prep-pack root. Generated files; do not edit.
"""
import re
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import make_fall2026_calendar as CAL  # noqa: E402

PACKS = Path.home() / "coding/courses/MathematicalPhysics/private/F2026PrepPacks"
AVAILABLE_DAYS_BEFORE = 10.5          # build_assignments.py
FIRST_CLASS = date(2026, 9, 9)

# ------------------------------------------------------------ logistics
# The bring / set-up list is checklist material (a checkbox, not prose),
# so it lives here as data rather than in the hand-written prep notes.
EVERY_DAY = [
    "iPad charged; AirPlay to the room display; GoodNotes instructor + class decks open",
    "Zoom recurring meeting joined from the iPad: recording badge showing, mic unmuted",
    "PCCI collection at the door; four-color voting cards for the comfort poll",
]
# date -> items specific to that day
DAY_LOGISTICS = {
    date(2026, 9, 9): ["Printed syllabus, one per student + spares",
                       "Printed math pretest (Pretest/MathPretest-student.pdf), one per student",
                       "Four-color voting cards, one set per student (shared/VotingCardLandscape.pdf)"],
    date(2026, 9, 25): ["Quiz 1: printed copies, both versions, + spares; per-problem score sheet"],
    date(2026, 9, 28): ["MacBook (HDMI) for the Python onboarding class; students bring laptops"],
    date(2026, 10, 23): ["Quiz 2: printed copies, both versions, + spares; per-problem score sheet"],
    date(2026, 11, 20): ["Quiz 3: printed copies, both versions, + spares; per-problem score sheet"],
}
# WHWs carrying a required computational problem (decided 2026-08-28;
# the problem text lives in private/MoodleBuild/whw-descriptions.html and
# SyllabusAndFirstDay/2026/ComputationalProblems.md).
COMPUTATIONAL = {2, 4, 5, 6, 8, 9, 10, 12, 13}


def fmt(d):
    return d.strftime("%a %b %-d")


def class_rows():
    days = list(CAL.class_days())
    content = iter(CAL.CONTENT)
    rows = []
    for i, d in enumerate(days):
        if i in CAL.SPECIALS:
            label, is_quiz = CAL.SPECIALS[i]
            rows.append((i + 1, d, label, "", is_quiz))
        else:
            topic, reading = next(content)
            rows.append((i + 1, d, topic, reading, False))
    return rows


def whw_events():
    days = list(CAL.class_days())
    out, hw_no = [], 0
    tiers = {w[0]: w for w in CAL.WHWS}
    for i, d in enumerate(days):
        if d.weekday() == 4 and i > 0:
            hw_no += 1
            due = CAL.WHW_DUE_OVERRIDE.get(hw_no, d)
            vis = max(due - timedelta(days=AVAILABLE_DAYS_BEFORE), FIRST_CLASS)
            out.append((hw_no, vis, vis + timedelta(days=1), due, tiers[hw_no]))
    return out


def checklist(row, all_rows, whws):
    n, d, topic, reading, is_quiz = row
    lines = [f"# Review checklist -- class {n:02d}, {fmt(d)} -- {topic}", "",
             "GENERATED by SyllabusAndFirstDay/2026/make_review_checklists.py from",
             "the calendar generator; rerun it after any change to PCCIs, WHWs, or",
             "the logistics table. Do not edit by hand.",
             "CHECKLIST = everything that is a checkbox (review items, deadlines,",
             "bring/set-up). PREP NOTES = the judgment (sources, errata, the timed",
             "plan, pacing).", ""]
    lines += ["## Before class (review these yourself first)", ""]
    pcci = CAL.PCCI.get(d)
    lines.append(f"- [ ] PCCI due today: **{pcci}**" if pcci else "- [ ] PCCI due today: none")
    if is_quiz:
        lines.append("- [ ] QUIZ DAY: the instrument, both versions, worked through end to end")
    else:
        lines.append("- [ ] In-class / group problems today: every problem named in this pack's"
                     " `00-prep-notes.md` plan (the generator does not hold 210's in-class"
                     " lists), worked yourself first")
    later = [r for r in all_rows if r[1] > d and CAL.PCCI.get(r[1])]
    if later:
        nd = later[0][1]
        lines.append(f"- [ ] Next PCCI (announce today, due {fmt(nd)}): {CAL.PCCI[nd]}")
    lines += ["", "## Homework (review every problem by the day after it goes live)", ""]
    prev_class = max([r[1] for r in all_rows if r[1] < d], default=None)
    any_hw = False
    for hw, vis, review_by, due, (wn, covers, warm, ess, depth) in whws:
        goes_live_now = (prev_class is None and vis <= d) or (prev_class is not None and prev_class < vis <= d)
        if goes_live_now:
            any_hw = True
            lines += [f"- [ ] **WHW{hw:02d} goes live {fmt(vis)}; review by {fmt(review_by)}** "
                      f"(due {fmt(due)}). Covers {covers}.",
                      f"      Warm-up: {warm}",
                      f"      Essentials: {ess}",
                      f"      Depth: {depth}"]
            if hw in COMPUTATIONAL:
                lines.append(f"      Computational: the required Python problem for WHW{hw:02d}"
                             " (ComputationalProblems.md) -- run it end to end on jupyterhub")
        if due == d:
            any_hw = True
            lines.append(f"- WHW{hw:02d} is DUE today 10:00 PM.")
    for ed, label in CAL.EXTRA_DUE.items():
        if ed == d:
            any_hw = True
            lines.append(f"- {label} today.")
    if not any_hw:
        lines.append("- nothing new goes live or comes due today")
    # ---- bring / set up
    lines += ["", "## Bring / set up", ""]
    for item in DAY_LOGISTICS.get(d, []):
        lines.append(f"- [ ] **{item}**")
    for item in EVERY_DAY:
        lines.append(f"- [ ] {item}")
    return "\n".join(lines) + "\n"


def main():
    rows = class_rows()
    whws = whw_events()
    packs = {int(p.name[:2]): p for p in PACKS.iterdir()
             if p.is_dir() and re.match(r"\d\d-", p.name)}
    written = 0
    sched = ["# Review schedule, whole semester (PHY 210 F2026)", "",
             "GENERATED by make_review_checklists.py; rerun after any generator edit.",
             "Rule: PCCIs and in-class problems reviewed BEFORE the class; WHW problems",
             "reviewed by THE DAY AFTER the assignment goes live.", ""]
    for row in rows:
        text = checklist(row, rows, whws)
        n = row[0]
        if n in packs:
            (packs[n] / "01-review-checklist.md").write_text(text)
            written += 1
        body = text.split("\n", 9)[9]
        sched += [f"## Class {n:02d} -- {fmt(row[1])} -- {row[2]}", "", body.strip(), ""]
    (PACKS / "REVIEW-SCHEDULE.md").write_text("\n".join(sched))
    print(f"wrote REVIEW-SCHEDULE.md ({len(rows)} days) and {written} pack checklists")


if __name__ == "__main__":
    main()
