"""Active-learning totals and semester roll-up for the prep packs (PHY 210).

Each `00-prep-notes.md` carries ONE timed plan: a `## Plan (75 min)`
section whose markdown table (Start, Stop, Min, Mode, What happens) is
the single source of truth for the day. This script validates every
table, rewrites that pack's `Totals:` line in place, and regenerates
`ACTIVE-LEARNING.md` at the prep-pack root. Rerun after editing any
plan:

    python make_active_learning.py

Both the `Totals:` lines and `ACTIVE-LEARNING.md` are generated; edit
the plan tables, never the derived numbers.
"""
import re
import sys
from pathlib import Path

PACKS = Path.home() / "coding/courses/MathematicalPhysics/private/F2026PrepPacks"
COURSE = "PHY 210"
MODES = ["Active", "Interactive", "Lecture", "Logistics"]
PERIOD = 75


def fail(msg):
    sys.exit(f"make_active_learning.py: {msg}")


def pack_files():
    """[(class_no, date, path)] for every NN-YYYY-MM-DD-* pack, in order."""
    out = []
    for d in sorted(PACKS.iterdir()):
        m = re.match(r"(\d\d)-(\d{4}-\d\d-\d\d)-", d.name) if d.is_dir() else None
        if m:
            out.append((int(m.group(1)), m.group(2), d / "00-prep-notes.md"))
    return out


def plan_rows(lines, path):
    """Parse the Plan table into [(start, stop, min, mode)]."""
    try:
        start = next(i for i, l in enumerate(lines) if l.strip() == "## Plan (75 min)")
    except StopIteration:
        fail(f"{path}: no '## Plan (75 min)' section")
    body = [l for l in lines[start:] if l.startswith("|")]
    if len(body) < 3:
        fail(f"{path}: no Plan table under '## Plan (75 min)'")
    rows = []
    for line in body[2:]:
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) != 5:
            fail(f"{path}: plan row has {len(cells)} columns, want 5: {line.strip()}")
        try:
            a, b, m = (int(cells[i]) for i in range(3))
        except ValueError:
            fail(f"{path}: non-integer Start/Stop/Min: {line.strip()}")
        rows.append((a, b, m, cells[3]))
    return rows


def check_rows(rows, path):
    prev = 0
    for a, b, m, mode in rows:
        where = f"{path}: row {a}-{b}"
        if a != prev:
            fail(f"{where}: starts at {a}, previous row stops at {prev}")
        if m != b - a:
            fail(f"{where}: Min {m} != Stop - Start ({b - a})")
        if m > 15:
            fail(f"{where}: Min {m} exceeds the 15-minute cap")
        if mode not in MODES:
            fail(f"{where}: unknown Mode {mode!r}; want one of {', '.join(MODES)}")
        prev = b
    if prev != PERIOD:
        fail(f"{path}: last Stop is {prev}, want {PERIOD}")


def totals(rows):
    return {mode: sum(m for _, _, m, md in rows if md == mode) for mode in MODES}


def totals_line(t):
    pct = round(100 * t["Active"] / PERIOD)
    return (f"Totals: Active {t['Active']} min ({pct}%), "
            f"Interactive {t['Interactive']}, Lecture {t['Lecture']}, "
            f"Logistics {t['Logistics']}, of {PERIOD}.")


def rewrite_totals(path, lines, line):
    for i, l in enumerate(lines):
        if l.startswith("Totals:"):
            lines[i] = line
            path.write_text("\n".join(lines) + "\n")
            return
    fail(f"{path}: no 'Totals:' line under the Plan table")


def topic(lines, path):
    h1 = next((l for l in lines if l.startswith("# ")), None)
    if h1 is None:
        fail(f"{path}: no H1 title line")
    return h1.lstrip("# ").split(" -- ")[-1].strip()


def cheapest_raise(lines, path):
    """The 'Cheapest raise:' paragraph, joined into one line."""
    for i, l in enumerate(lines):
        if l.startswith("Cheapest raise:"):
            para = [l]
            for nxt in lines[i + 1:]:
                if not nxt.strip():
                    break
                para.append(nxt.strip())
            text = " ".join(para)[len("Cheapest raise:"):].strip()
            return text[:1].upper() + text[1:]
    fail(f"{path}: no 'Cheapest raise:' line")


def render_table(header, rows):
    widths = [max(len(r[i]) for r in [header] + rows) for i in range(len(header))]
    def row(cells):
        return "| " + " | ".join(c.ljust(w) for c, w in zip(cells, widths)) + " |"
    return [row(header), row(["-" * w for w in widths])] + [row(r) for r in rows]


def header_lines():
    return [
        f"# Active learning in {COURSE}, Fall 2026",
        "",
        "GENERATED by SyllabusAndFirstDay/2026/make_active_learning.py from the",
        "`## Plan (75 min)` table in each pack's `00-prep-notes.md`, which is the",
        "single source of truth for the day. The script also writes each pack's",
        "`Totals:` line. Rerun it after editing any plan; do not edit the totals",
        "or this file by hand.",
        "",
        "## The four modes",
        "",
        "- **Active** -- students are doing the work: board work in groups,",
        "  think-pair-share, four-color voting-card polls, in-class work time,",
        "  notebook/laptop work, students presenting their own boards.",
        "- **Interactive** -- instructor-led derivation or explanation that is",
        "  explicitly elicited (questions to the room, predictions before the",
        "  reveal), but the instructor holds the pen.",
        "- **Lecture** -- instructor presents; students listen or copy.",
        "- **Logistics** -- announcements, syllabus, collection without",
        "  discussion, transitions.",
        "",
        "## Rules the tables follow",
        "",
        "1. Rows are contiguous from 0 to 75, Min = Stop - Start, and no row",
        "   exceeds 15 minutes; the script hard-fails otherwise.",
        "2. Every row's minutes land in exactly one mode. A chunk that mixes",
        "   modes is split into rows at the plan's own sentence boundaries, and",
        "   the split is named in that day's Ambiguities line.",
        "3. Ambiguous text is classified conservatively: Active only where the",
        "   plan says students do it and names the structure (pairs, groups of",
        "   three at the boards, voting cards, individual writing). Whole-class",
        "   question-and-answer is Interactive, not Active.",
        "4. Conditional activity (\"if the room is awake\") is credited to Active",
        "   but flagged, because it is also what the droppable tail eats first.",
        "5. Percentages are Active minutes over 75, rounded.",
        "",
        "Packs beyond the ones built so far get their table when the pack is",
        "built; there is nothing to count before then.",
        "",
        "## Per class day",
        "",
    ]


def main():
    table_rows, raises, sums, days = [], [], {m: 0 for m in MODES}, 0
    for n, date, path in pack_files():
        if not path.exists():
            fail(f"{path}: missing 00-prep-notes.md")
        lines = path.read_text().splitlines()
        rows = plan_rows(lines, path)
        check_rows(rows, path)
        t = totals(rows)
        rewrite_totals(path, lines, totals_line(t))
        table_rows.append([f"{n:02d}", date, topic(lines, path)]
                          + [str(t[m]) for m in MODES]
                          + [f"{round(100 * t['Active'] / PERIOD)}%"])
        raises.append(f"{n}. **Class {n:02d} ({date}).** {cheapest_raise(lines, path)}")
        for m in MODES:
            sums[m] += t[m]
        days += 1
    out = header_lines()
    out += render_table(["Class", "Date", "Topic"] + MODES + ["% Active"], table_rows)
    total = PERIOD * days
    out += ["", "Semester so far: " + ", ".join(
        f"{m} {sums[m]} min ({round(100 * sums[m] / total)}%)" for m in MODES)
        + f", of {total} min across {days} class days.", "",
        "## Cheapest raises", "",
        "The one change to each day's plan that buys the most Active minutes.",
        ""] + raises
    (PACKS / "ACTIVE-LEARNING.md").write_text("\n".join(out) + "\n")
    print(f"checked {days} packs, rewrote their Totals lines, wrote ACTIVE-LEARNING.md")


if __name__ == "__main__":
    main()
